[package]
name = "datafusion-postgres"
version = "0.3.0"
edition = "2021"
rust-version = "1.82.0"
description = "Exporting datafusion query engine with postgres wire protocol"
authors = ["Ning Sun <sunng@pm.me>"]
license = "Apache-2.0"
keywords = ["database", "postgresql"]
homepage = "https://github.com/sunng87/datafusion-postgres/"
repository = "https://github.com/sunng87/datafusion-postgres/"
documentation = "https://docs.rs/crate/datafusion-postgres/"
readme = "../README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgwire = { workspace = true }
datafusion = { workspace = true }
tokio = { version = "1.0", features = ["sync"] }
arrow = "54.2.0"
futures = "0.3"
async-trait = "0.1"
log = "0.4"
chrono = { version = "0.4", features = ["std"] }
